#!/usr/bin/env bash

echo "Installing clean submodule"

mv .git/modules .   && \
rm -rf .git/        && \
git init            && \
mv modules .git/    && \
git add jaoss       && \
rm $0               && \
git add .

echo "Submodule installed"

git status

echo "\x1b[1mPlease perform a commit now; e.g. git commit -m 'initial commit'\x1b[0m"
