#!/usr/bin/env bash

echo "Installing clean submodule"

mv .git/modules .   && \
rm -rf .git/        && \
git init            && \
mv modules .git/    && \
git add jaoss       && \
git add .gitmodules && \
rm $0

echo "Submodule installed"

git status
